=== uo296143/MotoGP-Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es"
	elementFormDefault="qualified">	
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" />
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="anchuraMedia" />
				<xs:element ref="fechaCarrera" />
				<xs:element ref="horaInicio" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="galeriaFotos" />
				<xs:element ref="galeriaVideos" />
				<xs:element ref="puntoOrigen" />
				<xs:element ref="tramos" />
				<xs:element ref="vencedor" />
				<xs:element ref="clasificacionMundial" />
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" />
			<xs:attribute ref="xml:lang" />
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="3000"/>
					<xs:maxInclusive value="6000"/>
					<xs:attribute name="unidad" use="required" fixed="metros" />
				</xs:restriction>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchuraMedia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="5"/>
					<xs:maxInclusive value="50"/>
					<xs:attribute name="unidad" use="required" fixed="metros" />
				</xs:restriction>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fechaCarrera">
		<xs:complexType>
			<xs:simpleContent>
				<xs:restriction base="xs:date">
					<xs:minInclusive value="2025-03-02"/>
					<xs:maxInclusive value="2025-11-16"/>
					<xs:attribute name="calendario">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="gregoriano" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:restriction>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="horaInicio">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:time">
					<xs:attribute name="zona" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="vueltas">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="20"/>
				<xs:maxInclusive value="30"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="ref" type="xs:anyURI"/>
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ref" minOccurs="3" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeriaFotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto">
		<xs:complexType>
			<xs:attribute name="archivo" type="xs:string" use="required" />
			<xs:attribute name="titulo" type="xs:string" />
			<xs:attribute name="tipo">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="jpg" />
						<xs:enumeration value="jpeg" />
						<xs:enumeration value="png" />
						<xs:enumeration value="gif" />
						<xs:enumeration value="webp" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeriaVideos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:attribute name="archivo" type="xs:string" use="required" />
			<xs:attribute name="titulo" type="xs:string" />
			<xs:attribute name="tipo">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="mp4" />
						<xs:enumeration value="mov" />
						<xs:enumeration value="mkv" />
						<xs:enumeration value="webm" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntoOrigen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudGeo" />
				<xs:element ref="latitudGeo" />
				<xs:element ref="altitudMSNM" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitudGeo" type="xs:string" />
	<xs:element name="latitudGeo" type="xs:string" />
	<xs:element name="altitudMSNM">
		<xs:complexType>
			<xs:simpleContent>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="0"/>
					<xs:maxInclusive value="2000"/>
					<xs:attribute name="unidad" use="required" fixed="metros" />
				</xs:restriction>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="puntoFinal" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="metros" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntoFinal">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudGeo" />
				<xs:element ref="latitudGeo" />
				<xs:element ref="altitudMSNM" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector" type="xs:string" />
	<xs:element name="vencedor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="piloto" />
				<xs:element ref="tiempoTotal" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="piloto" type="xs:string" />
	<xs:element name="tiempoTotal">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="formato">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="HH:MM:SS.mmm" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificacionMundial">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="pos1" />
				<xs:element ref="pos2" />
				<xs:element ref="pos3" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="pos1">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="piloto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="pos2">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="piloto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="pos3">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="piloto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntos">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="pts" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== uo296143/MotoGP-Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://www.uniovi.es"
  xsi:schemaLocation="http://www.uniovi.es circuito.xsd"
  version="1.0"
  xml:lang="es">

  <nombre>Autódromo Internacional de Termas de Río Hondo</nombre>

  <longitud unidad="metros">4806</longitud>
  <anchuraMedia unidad="metros">16</anchuraMedia>

  <fechaCarrera>2025-04-13</fechaCarrera>
  <horaInicio>20:00:00+01:00</horaInicio>

  <vueltas>25</vueltas>

  <localidad>Termas de Río Hondo</localidad>
  <pais>Argentina</pais>
  <patrocinador>Turismo Santiago del Estero</patrocinador>

  <referencias>
    <ref>https://es.wikipedia.org/wiki/Aut%C3%B3dromo_Internacional_de_Termas_de_R%C3%ADo_Hondo</ref>
    <ref>https://autodromotermas.com/</ref>
    <ref>
      https://www.dazn.com/es-ES/news/motor/circuito-de-termas-de-rio-hondo-donde-esta-como-es-caracteristicas-como-llegar-y-fotos-del-escenario-del-gp-de-argentina-del-mundial-de-motogp/1p956mqia2hde1i5jvq889bz0j</ref>
  </referencias>

  <galeriaFotos>
    <foto archivo="multimedia/panoramica-1.jpg" titulo="Panorámica 1" tipo="jpg" />
    <foto archivo="multimedia/panoramica-2.jpg" titulo="Panorámica 2" tipo="jpg" />
    <foto archivo="multimedia/panoramica-3.jpg" titulo="Panorámica 3" tipo="jpg" />
    <foto archivo="multimedia/panoramica-4.jpg" titulo="Panorámica 4" tipo="jpg" />
    <foto archivo="multimedia/argentina-motogp.jpg" titulo="Plano del circuito" tipo="jpg" />
  </galeriaFotos>

  <galeriaVideos>
    <video archivo="multimedia/patadaMarquez.mp4"
      titulo="Patada de Marc Marquez a Valentino Rossi"
      tipo="mp4" />
  </galeriaVideos>

  <!-- Coordenadas exactas del centro de la pista en la línea de salida -->
  <puntoOrigen>
    <longitudGeo>-64.91818905854689</longitudGeo>
    <latitudGeo>-27.51135130813497</latitudGeo>
    <altitudMSNM unidad="metros">285</altitudMSNM>
  </puntoOrigen>

  <!-- Tramos: ejemplo con distancias que suman la longitud total (4806 m).
       Coordenadas de punto final aproximadas para ilustración. -->
  <tramos>
    <tramo>
      <distancia unidad="metros">218</distancia>
      <puntoFinal>
        <longitudGeo>-64.916104</longitudGeo>
        <latitudGeo>-27.512013</latitudGeo>
        <altitudMSNM unidad="metros">282</altitudMSNM>
      </puntoFinal>
      <sector>1</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">64</distancia>
      <puntoFinal>
        <longitudGeo>-64.915884</longitudGeo>
        <latitudGeo>-27.512552</latitudGeo>
        <altitudMSNM unidad="metros">283</altitudMSNM>
      </puntoFinal>
      <sector>1</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">46</distancia>
      <puntoFinal>
        <longitudGeo>-64.915619</longitudGeo>
        <latitudGeo>-27.512896</latitudGeo>
        <altitudMSNM unidad="metros">284</altitudMSNM>
      </puntoFinal>
      <sector>1</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">39</distancia>
      <puntoFinal>
        <longitudGeo>-64.915222</longitudGeo>
        <latitudGeo>-27.512904</latitudGeo>
        <altitudMSNM unidad="metros">285</altitudMSNM>
      </puntoFinal>
      <sector>1</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">58</distancia>
      <puntoFinal>
        <longitudGeo>-64.915011</longitudGeo>
        <latitudGeo>-27.512421</latitudGeo>
        <altitudMSNM unidad="metros">286</altitudMSNM>
      </puntoFinal>
      <sector>1</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">99</distancia>
      <puntoFinal>
        <longitudGeo>-64.915115</longitudGeo>
        <latitudGeo>-27.511534</latitudGeo>
        <altitudMSNM unidad="metros">287</altitudMSNM>
      </puntoFinal>
      <sector>1</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">112</distancia>
      <puntoFinal>
        <longitudGeo>-64.915603</longitudGeo>
        <latitudGeo>-27.510623</latitudGeo>
        <altitudMSNM unidad="metros">288</altitudMSNM>
      </puntoFinal>
      <sector>1</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">171</distancia>
      <puntoFinal>
        <longitudGeo>-64.916428</longitudGeo>
        <latitudGeo>-27.509267</latitudGeo>
        <altitudMSNM unidad="metros">289</altitudMSNM>
      </puntoFinal>
      <sector>1</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">83</distancia>
      <puntoFinal>
        <longitudGeo>-64.916548</longitudGeo>
        <latitudGeo>-27.508525</latitudGeo>
        <altitudMSNM unidad="metros">290</altitudMSNM>
      </puntoFinal>
      <sector>1</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">54</distancia>
      <puntoFinal>
        <longitudGeo>-64.916381</longitudGeo>
        <latitudGeo>-27.508064</latitudGeo>
        <altitudMSNM unidad="metros">291</altitudMSNM>
      </puntoFinal>
      <sector>1</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">64</distancia>
      <puntoFinal>
        <longitudGeo>-64.915993</longitudGeo>
        <latitudGeo>-27.507608</latitudGeo>
        <altitudMSNM unidad="metros">281</altitudMSNM>
      </puntoFinal>
      <sector>1</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">53</distancia>
      <puntoFinal>
        <longitudGeo>-64.915528</longitudGeo>
        <latitudGeo>-27.507369</latitudGeo>
        <altitudMSNM unidad="metros">282</altitudMSNM>
      </puntoFinal>
      <sector>1</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">122</distancia>
      <puntoFinal>
        <longitudGeo>-64.914299</longitudGeo>
        <latitudGeo>-27.507249</latitudGeo>
        <altitudMSNM unidad="metros">283</altitudMSNM>
      </puntoFinal>
      <sector>2</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">90</distancia>
      <puntoFinal>
        <longitudGeo>-64.913473</longitudGeo>
        <latitudGeo>-27.506902</latitudGeo>
        <altitudMSNM unidad="metros">284</altitudMSNM>
      </puntoFinal>
      <sector>2</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">42</distancia>
      <puntoFinal>
        <longitudGeo>-64.913087</longitudGeo>
        <latitudGeo>-27.506732</latitudGeo>
        <altitudMSNM unidad="metros">285</altitudMSNM>
      </puntoFinal>
      <sector>2</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">39</distancia>
      <puntoFinal>
        <longitudGeo>-64.912712</longitudGeo>
        <latitudGeo>-27.506848</latitudGeo>
        <altitudMSNM unidad="metros">286</altitudMSNM>
      </puntoFinal>
      <sector>2</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">93</distancia>
      <puntoFinal>
        <longitudGeo>-64.912184</longitudGeo>
        <latitudGeo>-27.507538</latitudGeo>
        <altitudMSNM unidad="metros">287</altitudMSNM>
      </puntoFinal>
      <sector>2</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">130</distancia>
      <puntoFinal>
        <longitudGeo>-64.911424</longitudGeo>
        <latitudGeo>-27.50849</latitudGeo>
        <altitudMSNM unidad="metros">288</altitudMSNM>
      </puntoFinal>
      <sector>2</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">58</distancia>
      <puntoFinal>
        <longitudGeo>-64.911002</longitudGeo>
        <latitudGeo>-27.508856</latitudGeo>
        <altitudMSNM unidad="metros">289</altitudMSNM>
      </puntoFinal>
      <sector>2</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">53</distancia>
      <puntoFinal>
        <longitudGeo>-64.910492</longitudGeo>
        <latitudGeo>-27.508995</latitudGeo>
        <altitudMSNM unidad="metros">290</altitudMSNM>
      </puntoFinal>
      <sector>2</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">73</distancia>
      <puntoFinal>
        <longitudGeo>-64.909771</longitudGeo>
        <latitudGeo>-27.508856</latitudGeo>
        <altitudMSNM unidad="metros">291</altitudMSNM>
      </puntoFinal>
      <sector>2</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">45</distancia>
      <puntoFinal>
        <longitudGeo>-64.909468</longitudGeo>
        <latitudGeo>-27.508559</latitudGeo>
        <altitudMSNM unidad="metros">281</altitudMSNM>
      </puntoFinal>
      <sector>2</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">123</distancia>
      <puntoFinal>
        <longitudGeo>-64.910082</longitudGeo>
        <latitudGeo>-27.507598</latitudGeo>
        <altitudMSNM unidad="metros">282</altitudMSNM>
      </puntoFinal>
      <sector>2</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">152</distancia>
      <puntoFinal>
        <longitudGeo>-64.910899</longitudGeo>
        <latitudGeo>-27.506434</latitudGeo>
        <altitudMSNM unidad="metros">283</altitudMSNM>
      </puntoFinal>
      <sector>2</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">79</distancia>
      <puntoFinal>
        <longitudGeo>-64.911185</longitudGeo>
        <latitudGeo>-27.505771</latitudGeo>
        <altitudMSNM unidad="metros">284</altitudMSNM>
      </puntoFinal>
      <sector>3</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">97</distancia>
      <puntoFinal>
        <longitudGeo>-64.911279</longitudGeo>
        <latitudGeo>-27.504899</latitudGeo>
        <altitudMSNM unidad="metros">285</altitudMSNM>
      </puntoFinal>
      <sector>3</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">91</distancia>
      <puntoFinal>
        <longitudGeo>-64.910994</longitudGeo>
        <latitudGeo>-27.504124</latitudGeo>
        <altitudMSNM unidad="metros">286</altitudMSNM>
      </puntoFinal>
      <sector>3</sector>
    </tramo>
    <tramo>
      <distancia unidad="metros">60</distancia>
      <puntoFinal>
        <longitudGeo>-64.910651</longitudGeo>
        <latitudGeo>-27.503676</latitudGeo>
        <altitudMSNM unidad="metros">287</altitudMSNM>
      </puntoFinal>
      <sector>3</sector>
    </tramo>
    <tramo>
